### ISSUE TITLE
Unknown style, 'snip'

### ISSUE THREAD

**Issue by Julien00859** [jonathanpoelen/batrg#1]
Hello,

Just did download the repo as a zip and `cp`ed the `batrg` file to my locale `~/.locale/bin` which is in the PATH.

I have both `zsh`, `rg` and `bat` installed but running your command gives me the following error message:

    error: Invalid value for '--style <style-components>': Unknown style, 'snip'

What am I missing ?

**Comment by jonathanpoelen** [comment]
bat-0.13 >= is required. A workaround is to use `--no-snip` or `--style=numbers,header`.
